#!/usr/bin/env bash
# Single source of truth for invoking ``harness run`` over SSH with
# the correct outer wall-clock budget. Reads the SSOT via
# ``harness budget <suite>``, layers the documented buffers on top,
# and ensures the remote process is launched with ``setsid`` so the
# outer ``timeout`` can reap the whole process group instead of
# leaving sub-workers behind (the original incident root cause —
# GNU ``timeout`` only kills the direct child by default).
#
# Usage:
#   tools/remote_run.sh <suite> [extra harness run args...]
#
# Environment (consumed):
#   FORGE_CONFIG_DIR    per-loop config dir holding ``remote.toml``.
#   LOOP_ID             per-loop id.
#   Both are exported by ``agent-loop.sh`` / the web launcher.
#
# Override:
#   Pass ``--timeout SECS`` (or ``--timeout=SECS``) anywhere in the
#   extra args. The wrapper detects it, uses it as the new budget,
#   and recomputes the outer ssh-side ``timeout`` window so the
#   override is not silently truncated by a tighter outer guard.
#
# Layering (the only place these numbers may appear):
#   inner: dispatcher reads ``[evals.<suite>].timeout_s`` directly.
#   middle: transport adds a 60 s buffer for natural teardown.
#   outer (here): we add a further 120 s for ssh teardown / log
#                 flushing / result.json fetch. Total wrapper
#                 budget = effective + 180 s.
#
# RED LINE — see prompt/develop_prompt/remote-execution.md for the
# constraints on adding a literal ``timeout NNN`` anywhere else.

set -euo pipefail

# ── Per-workspace ``bin/harness`` shim PATH ─────────────────────────
# ``harness budget`` (below) and the remote ``harness run`` (further
# below) both depend on the workspace-local shim at
# ``<workspace>/bin/harness``. The shim is generated by
# ``agent-loop.sh`` at provision time and the wrapper exports
# ``PATH`` for its own children; but this script is also a public
# entry point for users reproducing the run by hand, who have no
# inherited PATH. Inject it unconditionally — when PATH already
# contains it this is a no-op.
_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_WORKSPACE_ROOT="$(dirname "$_SCRIPT_DIR")"
if [[ -x "$_WORKSPACE_ROOT/bin/harness" ]]; then
  export PATH="$_WORKSPACE_ROOT/bin:$PATH"
fi
unset _SCRIPT_DIR _WORKSPACE_ROOT

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 [--dry-run] [--poll] <suite> [extra harness run args...]" >&2
  exit 2
fi

# Leading flags (any order). --poll monitors an already-submitted job
# (kind=job only) instead of submitting a new one — the explicit
# continuation of a submit whose foreground poll hit the Bash timeout.
dry_run=0
poll=0
while [[ "$1" == "--dry-run" || "$1" == "--poll" ]]; do
  case "$1" in
    --dry-run) dry_run=1 ;;
    --poll)    poll=1 ;;
  esac
  shift
done

suite="$1"; shift

# Detect a user-supplied --timeout / --timeout=SECS in the extra args.
# We only honour the explicit override here — the regular extra args
# pass through unchanged to ``harness run`` on the remote side.
override=""
prev=""
for a in "$@"; do
  if [[ "$prev" == "--timeout" ]]; then
    override="$a"
  elif [[ "$a" == --timeout=* ]]; then
    override="${a#*=}"
  fi
  prev="$a"
done

# SSOT query — always quote ``harness budget`` instead of hardcoding.
# Any failure here (suite unknown, harness not on PATH) MUST abort the
# wrapper rather than fall back to a guessed default.
budget="$(harness budget "$suite")"
effective="${override:-$budget}"

# Outer budget = effective + transport_buffer (60) + ssh_teardown (120).
# The 120 s ssh-side allowance covers result.json rsync / ssh
# connection teardown after the remote ``harness run`` exits.
#
# NOTE on the kind="job" (cctl-job) path below: gpu_job.py treats ``outer``
# as the *execution* window anchored at the job's ``running`` transition,
# NOT at submission. The Queued phase is unbounded (the cluster may take
# arbitrarily long to schedule), so a scheduling backlog never eats this
# budget. On the ssh path ``outer`` keeps its original from-launch meaning
# (a held devspace has no queue, so launch == running).
outer=$(( effective + 60 + 120 ))

# ── Resolve remote host + workdir from remote.toml ──────────────────
# SSOT identical to ``harness/remote_sync.py:_resolve_remote_params``.
: "${FORGE_CONFIG_DIR:?required (run via agent-loop.sh)}"
: "${LOOP_ID:?required (run via agent-loop.sh)}"
_resolved=$(FORGE_CONFIG_DIR="$FORGE_CONFIG_DIR" LOOP_ID="$LOOP_ID" python3 - <<'__PY__'
import os, shlex, tomllib  # tomllib requires python3.11+
cfg = tomllib.load(open(os.environ["FORGE_CONFIG_DIR"] + "/remote.toml", "rb"))["remote"]
ws = (cfg.get("workspace") or "").strip() or "$HOME"
print(f'remote_host={shlex.quote(cfg["hostname"])}')
print(f'remote_workdir={shlex.quote(ws + "/.forge_train/" + os.environ["LOOP_ID"])}')
print(f'remote_kind={shlex.quote(str(cfg.get("kind") or "local"))}')
__PY__
)
eval "$_resolved"
# eval above assigns these three (also silences SC2154 by making the
# assignment visible to shellcheck); fail fast if the resolve broke.
: "${remote_host:?}" "${remote_workdir:?}" "${remote_kind:?}"

unset _resolved

# ── kind="job": submit the suite as an ephemeral cctl pytorchjob ─────
# In kind="job" the devspace is a 0-GPU filesystem gateway, so the suite
# cannot run on it via ssh. tools/gpu_job.py submits a cctl pytorchjob
# ([remote].nodes pods, default 1, of gpu_count GPUs each), runs the
# suite on the shared volume where `harness sync push` landed the code,
# and frees the GPUs on exit. The
# SSOT budget computed above (effective/outer) is handed to it — gpu_job
# never computes or hardcodes a budget itself (no-hardcoded-budgets lint).
if [[ "${remote_kind:-local}" == "job" ]]; then
  _ws_root="$(cd "$(dirname "$0")/.." && pwd)"
  export PYTHONPATH="${_ws_root}:${PYTHONPATH:-}"
  _gpu_job_flags=()
  [[ "$dry_run" == "1" ]] && _gpu_job_flags+=(--dry-run)
  [[ "$poll" == "1" ]] && _gpu_job_flags+=(--poll)
  # bash 3.2 (macOS /bin/bash): expanding an EMPTY array with set -u
  # raises "unbound variable" even after `arr=()` — guard the expansion.
  exec python3 -m tools.gpu_job ${_gpu_job_flags[@]+"${_gpu_job_flags[@]}"} "$suite" \
    --outer "$outer" --budget "$effective" -- "$@"
fi

# ``setsid`` on the remote side guarantees the remote ``harness`` and
# all its descendants share a fresh session/process-group so the
# remote-side kill (delivered via ssh disconnect) takes the whole
# tree down. This mirrors the local-side ``start_new_session=True``
# in ``harness/transport.py``.
#
# Persistent compile caches: Triton JIT + TorchInductor each rebuild
# their object files on every cold ssh hop unless TRITON_CACHE_DIR /
# TORCHINDUCTOR_CACHE_DIR point at a stable on-disk location. Loop
# e180edc7 Round 5 paid ~3 min compile/launch tax per long-train
# invocation; persisting both caches to $HOME/.cache amortises that
# tax across all subsequent harness runs (and survives ``cctl
# devspace copy`` since the user home volume is preserved). ``mkdir
# -p`` precedes the exports so the first invocation on a fresh
# devspace doesn't fail when Triton tries to write to a missing dir.
# PATH self-pin on the REMOTE side: the bare ``harness`` below is the
# per-workspace shim at <workdir>/bin/harness (synced with the code).
# A non-interactive ssh shell does not reliably source any profile, so
# relying on the remote environment to have put the shim on PATH breaks
# the moment the devspace/image changes (loop f6b9c438e05f round 9 —
# the agent then bypassed this wrapper and lost the budget + setsid
# guarantees). Pin it ourselves, mirroring the local self-inject above.
# LOOP_ID / FORGE_TRAIN_DIR must reach the remote runner or
# tools/mfu_record.py silently skips the mfu_history.jsonl append: the
# remote checkout is named <loop_id>, not "workspace", so the recorder's
# layout fallback never fires there and env is the only resolution path
# (remote-execution.md §Step 2 documents the same contract for manual
# ssh runs). Loop 9f03ffd324af deadlocked in long-horizon on exactly
# this gap — five passing full long-train runs, zero telemetry rows, so
# review could never issue MILESTONE_OVERRIDE.
remote_cmd="mkdir -p \"\$HOME/.cache/triton-persistent\" \"\$HOME/.cache/inductor-persistent\" && export TRITON_CACHE_DIR=\"\$HOME/.cache/triton-persistent\" TORCHINDUCTOR_CACHE_DIR=\"\$HOME/.cache/inductor-persistent\" && cd ${remote_workdir} && export PATH=\"\$PWD/bin:\$PATH\" && export LOOP_ID=${LOOP_ID} FORGE_TRAIN_DIR=${remote_workdir}/.artifacts/forge_train && exec setsid harness run ${suite} $*"

if [[ "$dry_run" == "1" ]]; then
  # Print the resolved budget + the would-be command, one field per
  # line, so the unit test can parse it without depending on shell
  # word-splitting of the embedded command string.
  printf 'kind=%s\n' "$remote_kind"
  printf 'budget=%s\n' "$budget"
  printf 'override=%s\n' "$override"
  printf 'effective=%s\n' "$effective"
  printf 'outer=%s\n' "$outer"
  printf 'remote_host=%s\n' "$remote_host"
  printf 'remote_workdir=%s\n' "$remote_workdir"
  printf 'suite=%s\n' "$suite"
  printf 'extra=%s\n' "$*"
  printf 'remote_cmd=%s\n' "$remote_cmd"
  exit 0
fi

exec timeout --kill-after=30 -s TERM "${outer}s" \
  ssh -o ServerAliveInterval=30 -o ServerAliveCountMax=4 "$remote_host" \
    "$remote_cmd"
